# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCloudCli < Formula
  desc "Jira CLI for Jira Cloud REST API v3"
  homepage "https://github.com/techinpark/jira-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techinpark/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "52fd80fbff1324208c9982d5198c2ce63528428c8fabb665489f3041af99dd45"

      define_method(:install) do
        system "go", "build", "-o", "jira-cloud-cli", "./main.go"
        bin.install "jira-cloud-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techinpark/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "24828177f535d3fd3635132b09554533af4aec7635bd6aaa69ccc8fb953a4410"

      define_method(:install) do
        system "go", "build", "-o", "jira-cloud-cli", "./main.go"
        bin.install "jira-cloud-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "cf18da3782df996610e2bc64b9e79b30f1db588fa70eada228c4b7661ba9090e"
      define_method(:install) do
        system "go", "build", "-o", "jira-cloud-cli", "./main.go"
        bin.install "jira-cloud-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "f27c4815fc8d57320bdf3526e1734a645aec92c3e5f218a95baa8ba980580369"
      define_method(:install) do
        system "go", "build", "-o", "jira-cloud-cli", "./main.go"
        bin.install "jira-cloud-cli"
      end
    end
  end
end
