# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaCli < Formula
  desc "Google Analytics 4 CLI tool — query DAU, events, countries, platforms, and realtime data from the terminal"
  homepage "https://github.com/techinpark/ga-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.1.0/ga-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "f422c19f2edbba049c606d8952e549c7bc51672d3b5cf97a903b02dd4b82e2bf"

      define_method(:install) do
        bin.install "ga-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.1.0/ga-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1cda26ef77875c25b04ff0ac6e5de6c7b3a69c1a9293be0da764a9e1173010fc"

      define_method(:install) do
        bin.install "ga-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.1.0/ga-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "057056b4612067e8db25b15260ae71ca38a14a0d156ad6476394d6ecd78bf0ac"
      define_method(:install) do
        bin.install "ga-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.1.0/ga-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "c654286d01411ce127c9ae71294eb2a603677a8d0db7954f017c72bc5f7151d2"
      define_method(:install) do
        bin.install "ga-cli"
      end
    end
  end

  test do
    system "#{bin}/ga-cli", "--version"
  end
end
