# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaCli < Formula
  desc "Google Analytics 4 CLI tool — query DAU, events, countries, platforms, and realtime data from the terminal"
  homepage "https://github.com/techinpark/ga-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.3.0/ga-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "07279682b40c022ccc8f2446fe3c5b3f36f1aa8cf7d6c6607ad5b0d63d6b3c3f"

      define_method(:install) do
        bin.install "ga-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.3.0/ga-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "91a937efba763f5f90dd932db1ebbf61c3587220e7747c476a37b7da7268b64c"

      define_method(:install) do
        bin.install "ga-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.3.0/ga-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "78b263776e223ea6ad3311e05b083e4ec57bc3aca3e0f917c0f2a01c515be483"
      define_method(:install) do
        bin.install "ga-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.3.0/ga-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "a7f9e715e385dab99665cc452bd15fdf357047cba785b59084b1315122f42b04"
      define_method(:install) do
        bin.install "ga-cli"
      end
    end
  end

  test do
    system "#{bin}/ga-cli", "--version"
  end
end
