# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaCli < Formula
  desc "Google Analytics 4 CLI tool — query DAU, events, countries, platforms, and realtime data from the terminal"
  homepage "https://github.com/techinpark/ga-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.2.0/ga-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "2d3fd240c3ec28475d20edbe5c7743bb4e3e6ae8bb59ced3b53ad7fd6792a8e8"

      define_method(:install) do
        bin.install "ga-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.2.0/ga-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "bc8188c3c599b6db49d2cfbff10f7495ca7076f8ee7713261eee5afc24c0666a"

      define_method(:install) do
        bin.install "ga-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.2.0/ga-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "9b1fbfb59c44c92657becb8b370569d2c9d6a70038e390deee713a1b36c29dc9"
      define_method(:install) do
        bin.install "ga-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techinpark/ga-cli/releases/download/v0.2.0/ga-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "cf18a60ea4e73977b003619770bf7164334668c6c723168dd4cfbdd09898b066"
      define_method(:install) do
        bin.install "ga-cli"
      end
    end
  end

  test do
    system "#{bin}/ga-cli", "--version"
  end
end
