# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kinolights < Formula
  desc "Kinolights CLI - 영화/드라마 정보 조회 도구"
  homepage "https://github.com/techinpark/kinolights"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/techinpark/kinolights/releases/download/v0.1.0/kinolights_0.1.0_darwin_amd64.tar.gz"
      sha256 "fa2db7be2e10e40a1adf6d4ad2daa0b243d6c0e3f0449741251922054fbefeec"

      def install
        bin.install "kinolights"
      end
    end
    on_arm do
      url "https://github.com/techinpark/kinolights/releases/download/v0.1.0/kinolights_0.1.0_darwin_arm64.tar.gz"
      sha256 "8cf70ecea985373fbd3d399c686b8b93a8690fca4a596eeec4a0d8314a8dd73e"

      def install
        bin.install "kinolights"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/techinpark/kinolights/releases/download/v0.1.0/kinolights_0.1.0_linux_amd64.tar.gz"
        sha256 "cae26e51be9659ceae4b97138485057bad3a6b4ac7e9d11e600b24eb67c9890b"

        def install
          bin.install "kinolights"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/techinpark/kinolights/releases/download/v0.1.0/kinolights_0.1.0_linux_arm64.tar.gz"
        sha256 "8a9e62b8ffba0b3cce1ca44c741ffdfc607b2e3e9d715eae5fce4ce4b0b37d31"

        def install
          bin.install "kinolights"
        end
      end
    end
  end

  test do
    system "#{bin}/kinolights", "--help"
  end
end
